# Generated by Django 3.0.7 on 2020-06-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='staff',
        ),
    ]
