# Generated by Django 3.0.7 on 2020-06-24 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200619_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_teacher',
            new_name='is_mentor',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='full_name',
            new_name='username',
        ),
    ]
