# Generated by Django 3.0.7 on 2020-06-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='default.jpeg', upload_to='profiles'),
        ),
    ]
